/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LIBRARY_PACKAGE;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rlith
 */
public class STUDENT_REGISTRATION extends javax.swing.JFrame {
    
    
        
    public STUDENT_REGISTRATION() {
        initComponents();
        setDefaultCloseOperation(STUDENT_REGISTRATION.DISPOSE_ON_CLOSE);
    }

    
    public void clear(){
        USER_ID.setText(null);
        USER_NAME.setText(null);
        BRANCH.setSelectedItem(null);
        DEPARTMENT.setSelectedItem(null);
        SEMESTER.setSelectedItem(null);
        MOBILE_NUMBER.setText(null);
        EMAIL.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        USER_ID = new javax.swing.JTextField();
        USER_NAME = new javax.swing.JTextField();
        MOBILE_NUMBER = new javax.swing.JTextField();
        EMAIL = new javax.swing.JTextField();
        RESET = new javax.swing.JButton();
        SAVE = new javax.swing.JButton();
        SEMESTER = new javax.swing.JComboBox<>();
        BRANCH = new javax.swing.JComboBox<>();
        DEPARTMENT = new javax.swing.JComboBox<>();
        CANCEL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("STUDENT REGISTRATION");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Student ID");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Branch");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Semester");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Email");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Mobile Number");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Department");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Student Name");

        USER_ID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        USER_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USER_IDActionPerformed(evt);
            }
        });

        USER_NAME.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        USER_NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USER_NAMEActionPerformed(evt);
            }
        });

        MOBILE_NUMBER.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MOBILE_NUMBER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOBILE_NUMBERActionPerformed(evt);
            }
        });

        EMAIL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMAILActionPerformed(evt);
            }
        });

        RESET.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RESET.setText("RESET");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });

        SAVE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });

        SEMESTER.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SEMESTER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "I", "II", "III ", "IV ", "V", "VI", "VII", "VIII " }));
        SEMESTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEMESTERActionPerformed(evt);
            }
        });

        BRANCH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BRANCH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "B.E. ", "B.Tech. ", "M.E. ", "M.Tech.", "MBA ", "MCA ", "B.Sc.", "M.Sc. ", "BBA", "BCA ", "Ph.D" }));
        BRANCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRANCHActionPerformed(evt);
            }
        });

        DEPARTMENT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DEPARTMENT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "CSE", "IT ", "ECE", "EEE", "MECH ", "CIVIL ", "AI&DS", "AI&ML", "BCOM ", "BCA ", "BSC IT ", "BSC CS", "BSC MAT", "BSC PHY ", "ENG", "TAM", "HIS ", "ECO ", "BBA " }));
        DEPARTMENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEPARTMENTActionPerformed(evt);
            }
        });

        CANCEL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CANCEL.setText("CANCEL");
        CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(279, 279, 279))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(388, 388, 388))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SAVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(66, 66, 66))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(USER_ID)
                            .addComponent(BRANCH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EMAIL)
                            .addComponent(MOBILE_NUMBER)
                            .addComponent(USER_NAME)
                            .addComponent(SEMESTER, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DEPARTMENT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RESET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(61, 61, 61)
                                .addComponent(CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(USER_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(USER_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BRANCH, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SEMESTER, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DEPARTMENT, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MOBILE_NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void USER_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USER_IDActionPerformed
        
    }//GEN-LAST:event_USER_IDActionPerformed

    private void USER_NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USER_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USER_NAMEActionPerformed

    private void MOBILE_NUMBERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOBILE_NUMBERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MOBILE_NUMBERActionPerformed

    private void EMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMAILActionPerformed

    private void SEMESTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEMESTERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEMESTERActionPerformed

    private void BRANCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRANCHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BRANCHActionPerformed

    private void DEPARTMENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEPARTMENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DEPARTMENTActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/LIBRARY_MANAGEMENT_SYSTEM";
        String user = "root";
        String pass = "Lithiyasree12@";
        
         try (Connection conn = DriverManager.getConnection(url, user, pass)) {
        if (USER_ID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter Student ID");
            USER_ID.requestFocus();
        } else if (USER_NAME.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter Student Name");
            USER_NAME.requestFocus();
        } else if (BRANCH.getSelectedItem() == null || BRANCH.getSelectedItem().toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter Branch");
            BRANCH.requestFocus();
        } else if (SEMESTER.getSelectedItem() == null || SEMESTER.getSelectedItem().toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter Semester");
            SEMESTER.requestFocus();
        } else if (DEPARTMENT.getSelectedItem() == null || DEPARTMENT.getSelectedItem().toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter Department");
            DEPARTMENT.requestFocus();
        } else if (MOBILE_NUMBER.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter Mobile Number");
            MOBILE_NUMBER.requestFocus();
        } else if (EMAIL.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please enter Email");
            EMAIL.requestFocus();
        } else {
            String query = "INSERT INTO USER (USER_ID, USER_NAME, BRANCH, SEMESTER, DEPARTMENT, MOBILE, EMAIL, USER_TYPE) VALUES (?, ?, ?, ?, ?, ?, ?, 'STUDENT')";

            try (PreparedStatement pst = conn.prepareStatement(query)) {
                pst.setString(1, USER_ID.getText().trim());
                pst.setString(2, USER_NAME.getText().trim());
                pst.setString(3, BRANCH.getSelectedItem().toString().trim());
                pst.setString(4, SEMESTER.getSelectedItem().toString().trim());
                pst.setString(5, DEPARTMENT.getSelectedItem().toString().trim());
                pst.setString(6, MOBILE_NUMBER.getText().trim());
                pst.setString(7, EMAIL.getText().trim());

                int rowsInserted = pst.executeUpdate();
                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Record Saved", "Saved", JOptionPane.INFORMATION_MESSAGE);
                    clear();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error updating database: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error connecting to database: " + e.getMessage(), "Connection Error", JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_SAVEActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_RESETActionPerformed

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CANCELActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STUDENT_REGISTRATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(STUDENT_REGISTRATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(STUDENT_REGISTRATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(STUDENT_REGISTRATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STUDENT_REGISTRATION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BRANCH;
    private javax.swing.JButton CANCEL;
    private javax.swing.JComboBox<String> DEPARTMENT;
    private javax.swing.JTextField EMAIL;
    private javax.swing.JTextField MOBILE_NUMBER;
    private javax.swing.JButton RESET;
    private javax.swing.JButton SAVE;
    private javax.swing.JComboBox<String> SEMESTER;
    private javax.swing.JTextField USER_ID;
    private javax.swing.JTextField USER_NAME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
